import React from 'react';
import { PropsWithChildren } from "react";
import "./globals.css";
import Link from 'next/link'

export default async function RootLayout({ children }: PropsWithChildren) {
  return (<html>
    <body>
      <br></br>
      <Link href="/">처음으로</Link> <br></br>
      {children}
      <br></br>
    </body></html>)
}
export const metadata = {
  title: "4294967295.io",
  description: "Generated by 4294967295",
  icons: {
    icon: "/4.png",
  }
}
