import React from 'react';
import { PropsWithChildren } from "react";
import "./globals.css";
import Link from 'next/link'

export default async function RootLayout({ children }: PropsWithChildren) {
  return (<html>
    <body> <Link href="/create">의견개진란</Link>
      <br></br>
      {children}
      <br></br>
      발생하는 모든 문제는 사용자 문제입니다.</body></html>)


  /*
 /* const res = await fetch('http://localhost:3000/api')
  const topics = await res.json();
 
  return (
      <html>
        <body>
        <h1><Link href="/">test</Link></h1><br></br>
        아직 mysql연동 안해서 글쓰기 안될것임.(서버끔)
        <ol>
       {topics.map((topic)=>{
         return<li key={topic.id}><Link href={'/read2'}>{topic.title}</Link></li>
          return<li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
         })}
        </ol>
          {children}
          <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update/1">update</Link></li>
        </ol>  <li><input type="button" value="delete"/></li>
      </body>  </ul>
          </body>
      </html>
    );
  }
  */
}
export const metadata = {
  title: "4294967295.io",
  description: "Generated by 4294967295",
  icons: {
    icon: "/4.png",
  }
}
